<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Tax Invoice {{ $invoice_number }}</title>
  <style>
    @page { margin: 22mm 16mm; }
    body { font-family: DejaVu Sans, sans-serif; color: #1c2430; font-size: 10.5px; }
    .head { display: flex; border-bottom: 3px solid #b8912f; padding-bottom: 10px; margin-bottom: 14px; }
    .head h1 { margin: 0; font-size: 16px; letter-spacing: 1px; }
    .head small { color: #8a6d1f; letter-spacing: 2px; font-size: 8.5px; }
    .head .inv { text-align: right; }
    .head .inv strong { font-size: 13px; }
    .party { width: 100%; border-collapse: collapse; margin-bottom: 12px; }
    .party td { width: 50%; border: 1px solid #d8dce4; padding: 8px 10px; vertical-align: top; }
    .party .k { color: #4a5568; font-weight: bold; font-size: 9px; }
    table.lines { width: 100%; border-collapse: collapse; }
    table.lines th { background: #0e1726; color: #e7c56a; padding: 7px 10px; font-size: 9.5px; text-align: left; }
    table.lines td { border: 1px solid #d8dce4; padding: 7px 10px; font-size: 10px; }
    .totals td { text-align: right; }
    .grand td { font-weight: bold; font-size: 12px; background: #f4f6fa; }
    .zatca { border: 2px solid #0e8f84; border-radius: 6px; padding: 12px; margin-top: 14px; background: #f0fbfa; }
    .zatca table td { border: none; vertical-align: top; }
    .qr { width: 120px; height: 120px; }
    .mono { font-family: DejaVu Sans Mono, monospace; font-size: 8.5px; word-break: break-all; }
    .badge { display: inline-block; background: #0e8f84; color: #fff; padding: 3px 10px; border-radius: 10px; font-size: 9px; font-weight: bold; }
    .foot { margin-top: 18px; border-top: 1px solid #d8dce4; padding-top: 8px; font-size: 8px; color: #7a8494; text-align: center; }
  </style>
</head>
<body>
  <div class="head">
    <div style="flex:1">
      <h1>NAWADER SOVEREIGN SERVICES</h1>
      <small>VAT No. 302910492800003 &middot; RIYADH, KINGDOM OF SAUDI ARABIA</small>
    </div>
    <div class="inv">
      <strong>TAX INVOICE — فاتورة ضريبية</strong><br>
      <span class="mono">{{ $invoice_number }}</span><br>
      {{ now()->format('Y-m-d H:i') }} (+03:00)
    </div>
  </div>

  <table class="party">
    <tr>
      <td>
        <span class="k">SUPPLIER</span><br>
        Nawader Sovereign Services Co.<br>
        VAT: 302910492800003<br>
        CSID: <span class="mono">{{ $payload['csid'] }}</span>
      </td>
      <td>
        <span class="k">CUSTOMER</span><br>
        {{ $request->user?->name ?? '—' }}<br>
        {{ $request->entity_name ?: 'Individual client' }}<br>
        Request: <span class="mono">{{ $request->request_number }}</span>
      </td>
    </tr>
  </table>

  <table class="lines">
    <tr><th>Description</th><th style="width:18%">Qty</th><th style="width:22%">Amount (SAR)</th></tr>
    <tr>
      <td>Sovereign service engagement — registered under request {{ $request->request_number }} (Arabic details in the client dashboard). Track: {{ $request->speed }}.</td>
      <td>1</td>
      <td>{{ number_format($net, 2) }}</td>
    </tr>
  </table>

  <table class="lines totals">
    <tr><td style="width:70%">Subtotal (excluding VAT)</td><td>{{ number_format($net, 2) }} SAR</td></tr>
    <tr><td>VAT @ 15%</td><td>{{ number_format($vat, 2) }} SAR</td></tr>
    <tr class="grand"><td>TOTAL (VAT INCLUSIVE)</td><td>{{ number_format($total, 2) }} SAR</td></tr>
  </table>

  <div class="zatca">
    <table style="width:100%">
      <tr>
        <td width="60%">
          <span class="badge">ZATCA PHASE-2 CLEARED</span>
          <p style="font-size:9px;margin:8px 0 0;">
            Invoice hash (SHA-256):<br><span class="mono">{{ $payload['invoice_hash'] }}</span><br>
            XML signed: YES &middot; Compliance: {{ $payload['compliance_status'] }}<br>
            Settlement: Sovereign Escrow {{ $request->escrow_reference }} — fully collected.
          </p>
        </td>
        <td width="40%" style="text-align:center">
          {!! $qrDataUri !!}
          <div style="font-size:7.5px" class="mono">TLV / Base64 Phase-2 QR</div>
        </td>
      </tr>
    </table>
  </div>

  <p style="font-size:9px;color:#4a5568;margin-top:10px;">
    Loyalty: {{ number_format((int) (($request->price_base + $request->price_speed_fee) / 10), 0) }} loyalty points awarded to the customer account upon issuance of this final invoice.
  </p>

  <div class="foot">This invoice is machine-generated by the Nawader sovereign invoicing engine under ZATCA Phase-2 (Fatoora) regulations &middot; {{ $invoice_number }}</div>
</body>
</html>
