@extends('layouts.app')
@section('title', 'الإشعارات — نوادر')
@section('page_title', 'الإشعارات')
@push('head')
<style>.nw-notifications-page{max-width:960px;margin:auto;padding:120px 28px 80px}.nw-notification-card{border-radius:20px;padding:1.2rem 1.35rem;margin-bottom:.75rem;display:flex;gap:1rem;align-items:start}.nw-notification-card.unread{border-color:rgba(212,168,67,.42);background:linear-gradient(120deg,rgba(212,168,67,.11),rgba(14,23,42,.88))}.nw-notification-icon{width:38px;height:38px;border-radius:12px;background:rgba(0,212,200,.12);display:grid;place-items:center;flex:0 0 auto}@media(max-width:640px){.nw-notifications-page{padding:90px 18px 60px}}</style>
@endpush
@section('content')
<main class="nw-notifications-page"><header style="display:flex;justify-content:space-between;align-items:end;gap:1rem;margin-bottom:1.25rem"><div><div class="nw-section-eyebrow">التحديثات</div><h1 class="nw-h1" style="margin:.55rem 0">مركز الإشعارات</h1><p style="color:var(--text-secondary)">رسائل مرتبطة فعلياً بحسابك وطلباتك.</p></div><form method="POST" action="{{route('dashboard.notifications.read')}}">@csrf<button class="nw-btn nw-btn-ghost nw-btn-sm" type="submit">تحديد الكل كمقروء</button></form></header>@if(session('success'))<div class="nw-cinematic-panel" style="padding:1rem;margin-bottom:1rem;color:var(--nawader-teal)">{{session('success')}}</div>@endif
@forelse($items as $item)<article class="nw-notification-card nw-cinematic-panel {{$item->read_at ? '' : 'unread'}}"><div class="nw-notification-icon">{{$item->type === 'success' ? '✓' : 'i'}}</div><div style="flex:1"><div style="display:flex;justify-content:space-between;gap:1rem;align-items:start"><strong>{{$item->title}}</strong><small style="color:var(--text-muted);white-space:nowrap">{{$item->created_at->diffForHumans()}}</small></div><p style="color:var(--text-secondary);font-size:.86rem;margin:.4rem 0">{{$item->body}}</p>@if($item->action_url)<a href="{{$item->action_url}}" style="font-size:.8rem;color:var(--nawader-gold)">فتح التفاصيل</a>@endif</div></article>@empty<div class="nw-empty nw-cinematic-panel">لا توجد إشعارات لهذا الحساب حتى الآن.</div>@endforelse{{$items->links()}}</main>
@endsection
