@extends('layouts.app')
@section('title', 'الملف الشخصي — نوادر')
@section('page_title', 'الملف الشخصي')
@push('head')
<style>.nw-account-page{max-width:940px;margin:auto;padding:120px 28px 80px}.nw-account-card{border-radius:26px;padding:clamp(1.4rem,4vw,2.5rem)}.nw-account-form{display:grid;grid-template-columns:1fr 1fr;gap:1.2rem}.nw-account-field{display:flex;flex-direction:column;gap:.45rem}.nw-account-field label{font-size:.82rem;color:var(--text-secondary)}.nw-account-field input{width:100%}.nw-account-note{margin-top:1.4rem;padding:1rem;border-radius:14px;background:rgba(0,212,200,.07);border:1px solid rgba(0,212,200,.2);font-size:.84rem;color:var(--text-secondary)}@media(max-width:640px){.nw-account-page{padding:90px 18px 60px}.nw-account-form{grid-template-columns:1fr}}</style>
@endpush
@section('content')
<main class="nw-account-page"><header style="margin-bottom:1.25rem"><div class="nw-section-eyebrow">الحساب</div><h1 class="nw-h1" style="margin:.55rem 0">بياناتك الأساسية</h1><p style="color:var(--text-secondary)">حدّث المعلومات التي تستخدمها نوادر للتواصل بشأن طلباتك.</p></header>@if(session('success'))<div class="nw-cinematic-panel" style="padding:1rem;margin-bottom:1rem;color:var(--nawader-teal)">{{session('success')}}</div>@endif
<section class="nw-account-card nw-cinematic-panel"><div style="display:flex;align-items:center;gap:1rem;margin-bottom:1.5rem"><img class="nw-cinematic-emblem" src="{{ asset('images/cinematic/nawader-moon-emblem-v1.webp') }}" alt=""><div><h2 class="nw-h3">الملف الشخصي</h2><p style="font-size:.82rem;color:var(--text-muted)">بيانات محفوظة بشكل خاص ضمن حسابك.</p></div></div><form method="POST" action="{{route('dashboard.profile.update')}}">@csrf @method('PUT')<div class="nw-account-form"><div class="nw-account-field"><label for="name">الاسم</label><input id="name" class="nw-input" name="name" value="{{old('name',$user->name)}}" required></div><div class="nw-account-field"><label for="company_name">اسم المنشأة (اختياري)</label><input id="company_name" class="nw-input" name="company_name" value="{{old('company_name',$user->company_name)}}"></div><div class="nw-account-field"><label>البريد الإلكتروني</label><input class="nw-input" value="{{$user->email}}" readonly aria-readonly="true"></div><div class="nw-account-field"><label for="phone">رقم الجوال</label><input id="phone" class="nw-input" name="phone" value="{{old('phone',$user->phone)}}" inputmode="tel"></div></div><div class="nw-account-note">لتغيير البريد الإلكتروني أو التحقق من الجوال، استخدم إعدادات الأمان حتى تظل هوية الحساب محمية.</div><div style="margin-top:1.4rem"><button class="nw-btn nw-btn-primary" type="submit">حفظ التغييرات</button></div></form></section></main>
@endsection
