@extends('layouts.app')
@section('title', 'تتبع الطلب — نوادر')
@section('page_title', 'تتبع الطلب')
@push('head')
<style>.nw-track-page{max-width:900px;margin:auto;padding:120px 28px 80px}.nw-track-card{border-radius:28px;padding:clamp(1.5rem,4vw,2.5rem)}.nw-track-rail{margin-top:2rem;padding-right:1.4rem;border-right:1px solid rgba(212,168,67,.35)}.nw-track-step{position:relative;padding:0 1.4rem 1.8rem}.nw-track-step::before{content:'';position:absolute;width:12px;height:12px;border-radius:50%;right:-1.78rem;top:.35rem;background:var(--nawader-teal);box-shadow:0 0 0 5px rgba(0,212,200,.13)}.nw-track-step.future::before{background:rgba(255,255,255,.25);box-shadow:none}@media(max-width:640px){.nw-track-page{padding:90px 18px 60px}}</style>
@endpush
@section('content')
<main class="nw-track-page"><a href="{{route('dashboard.requests.show',$operation->request_number)}}" style="display:inline-block;color:var(--nawader-gold);margin-bottom:1rem">← تفاصيل الطلب</a><section class="nw-track-card nw-cinematic-panel"><div class="nw-section-eyebrow">{{ $operation->request_number }}</div><h1 class="nw-h1" style="margin:.55rem 0">مسار الطلب</h1><p style="color:var(--text-secondary)">المراحل أدناه مشتقة من الحالة الحالية للطلب، وليست اتصالاً مباشراً بأي جهة خارجية.</p><div class="nw-progress" style="height:8px;margin-top:1.4rem"><i style="width:{{ $operation->progress }}%"></i></div><div class="nw-track-rail"><article class="nw-track-step"><strong>تم استلام الطلب</strong><p style="color:var(--text-muted);font-size:.84rem;margin-top:.25rem">{{ $operation->submitted_at?->format('Y/m/d H:i') }}</p></article><article class="nw-track-step {{ $operation->progress < 30 ? 'future' : '' }}"><strong>المراجعة الأولية</strong><p style="color:var(--text-muted);font-size:.84rem;margin-top:.25rem">تُحدّث عند بدء المراجعة من فريق العمل.</p></article><article class="nw-track-step {{ $operation->progress < 70 ? 'future' : '' }}"><strong>التنفيذ والمتابعة</strong><p style="color:var(--text-muted);font-size:.84rem;margin-top:.25rem">الحالة الحالية: {{ $operation->statusLabel() }}</p></article><article class="nw-track-step {{ $operation->status !== 'completed' ? 'future' : '' }}"><strong>الإنجاز والإغلاق</strong><p style="color:var(--text-muted);font-size:.84rem;margin-top:.25rem">تظهر عند اكتمال الطلب وتوثيق النتيجة.</p></article></div></section></main>
@endsection
