@extends('layouts.app')
@section('title', 'تفاصيل الطلب — نوادر')
@section('page_title', 'تفاصيل الطلب')
@push('head')
<style>.nw-request-page{max-width:980px;margin:auto;padding:120px 28px 80px}.nw-request-card{border-radius:26px;padding:clamp(1.4rem,4vw,2.4rem);margin-bottom:1rem}.nw-request-detail{display:grid;grid-template-columns:repeat(2,1fr);gap:1rem}.nw-request-detail div{padding:1rem;border-radius:15px;background:rgba(255,255,255,.035)}.nw-request-detail small{display:block;color:var(--text-muted);margin-bottom:.25rem}@media(max-width:640px){.nw-request-page{padding:90px 18px 60px}.nw-request-detail{grid-template-columns:1fr}}</style>
@endpush
@section('content')
<main class="nw-request-page">@if(session('success'))<div class="nw-cinematic-panel" style="padding:1rem;margin-bottom:1rem;color:var(--nawader-teal)">{{session('success')}}</div>@endif
<a href="{{route('dashboard.requests')}}" style="display:inline-block;color:var(--nawader-gold);margin-bottom:1rem">← العودة إلى الطلبات</a><section class="nw-request-card nw-cinematic-panel"><div style="display:flex;justify-content:space-between;gap:1rem;flex-wrap:wrap"><div><div class="nw-section-eyebrow">{{ $operation->request_number }}</div><h1 class="nw-h1" style="margin:.55rem 0">{{ $operation->service_name }}</h1><p style="color:var(--text-secondary)">هذا السجل يعرض تفاصيل الطلب كما أرسلته وحالته الحالية.</p></div><span class="nw-status" style="height:max-content">{{ $operation->statusLabel() }}</span></div><div class="nw-progress" style="height:8px;margin:1.5rem 0 .5rem"><i style="width:{{ $operation->progress }}%"></i></div><div style="color:var(--text-muted);font-size:.8rem">نسبة التقدم المسجلة: {{ $operation->progress }}%</div></section>
<section class="nw-request-card nw-cinematic-panel"><h2 class="nw-h3" style="margin-bottom:1rem">بيانات الطلب</h2><div class="nw-request-detail"><div><small>المنشأة</small>{{ $operation->entity_name ?: '—' }}</div><div><small>السوق المستهدف</small>{{ $operation->target_market ?: '—' }}</div><div><small>سرعة التنفيذ</small>{{ $operation->speed }}</div><div><small>تاريخ الإرسال</small>{{ $operation->submitted_at?->format('Y/m/d H:i') }}</div></div>@if($operation->notes)<div style="margin-top:1rem;padding:1rem;border-radius:15px;background:rgba(255,255,255,.035)"><small style="color:var(--text-muted);display:block;margin-bottom:.25rem">ملاحظاتك</small>{{ $operation->notes }}</div>@endif</section>
<section class="nw-request-card nw-cinematic-panel"><div style="display:flex;justify-content:space-between;align-items:center;gap:1rem"><div><h2 class="nw-h3">المستندات</h2><p style="color:var(--text-muted);font-size:.82rem">{{ count($operation->documents ?? []) }} ملف مرفق</p></div><a class="nw-btn nw-btn-ghost nw-btn-sm" href="{{ route('dashboard.requests.track',$operation->request_number) }}">عرض المسار</a></div>@if(count($operation->documents ?? []))<ul style="margin-top:1rem">@foreach($operation->documents as $document)<li style="padding:.65rem 0;border-bottom:1px solid rgba(255,255,255,.07)">📎 {{ $document['name'] }}</li>@endforeach</ul>@else<div class="nw-empty" style="margin-top:1rem;padding:1.3rem">لم تُرفق مستندات مع هذا الطلب.</div>@endif</section></main>
@endsection
