@extends('layouts.app')
@section('title', 'الأمان والإعدادات — نوادر')
@section('page_title', 'الأمان والإعدادات')
@push('head')
<style>.nw-settings-page{max-width:940px;margin:auto;padding:120px 28px 80px}.nw-settings-card{border-radius:26px;padding:clamp(1.4rem,4vw,2.4rem);margin-bottom:1rem}.nw-setting-row{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding:1.1rem 0;border-bottom:1px solid rgba(255,255,255,.08)}.nw-setting-row:last-child{border:0}.nw-toggle{width:46px;height:26px;appearance:none;border-radius:99px;background:rgba(255,255,255,.16);position:relative;transition:.2s}.nw-toggle::after{content:'';position:absolute;width:20px;height:20px;border-radius:50%;background:#fff;top:3px;right:3px;transition:.2s}.nw-toggle:checked{background:var(--nawader-teal)}.nw-toggle:checked::after{right:23px}@media(max-width:640px){.nw-settings-page{padding:90px 18px 60px}}</style>
@endpush
@section('content')
<main class="nw-settings-page"><header style="margin-bottom:1.25rem"><div class="nw-section-eyebrow">الحماية</div><h1 class="nw-h1" style="margin:.55rem 0">أمان الحساب</h1><p style="color:var(--text-secondary)">اضبط خيارات الدخول والحماية من مكان واحد.</p></header>@if(session('success'))<div class="nw-cinematic-panel" style="padding:1rem;margin-bottom:1rem;color:var(--nawader-teal)">{{session('success')}}</div>@endif
<form method="POST" action="{{route('dashboard.settings.update')}}">@csrf @method('PUT')<section class="nw-settings-card nw-cinematic-panel"><div class="nw-setting-row"><div><strong>تفعيل التحقق الإضافي</strong><p style="font-size:.82rem;color:var(--text-muted);margin-top:.2rem">تظهر لك خطوة تحقق إضافية عند دخول حسابك.</p></div><input class="nw-toggle" type="checkbox" name="two_factor_enabled" value="1" {{ $user->two_factor_enabled ? 'checked' : '' }} aria-label="تفعيل التحقق الإضافي"></div><div class="nw-setting-row"><div><strong>التحقق برقم الجوال</strong><p style="font-size:.82rem;color:var(--text-muted);margin-top:.2rem">اربط رقمك عبر واتساب أو رمز QR لتقوية استرداد الحساب.</p></div><a class="nw-btn nw-btn-ghost nw-btn-sm" href="{{route('dashboard.security.phone')}}">إدارة الرقم</a></div><div style="margin-top:1.25rem"><button type="submit" class="nw-btn nw-btn-primary">حفظ إعدادات الأمان</button></div></section></form></main>
@endsection
