@extends('layouts.app')
@section('title', 'المحفظة — نوادر')
@section('page_title', 'المحفظة')
@push('head')
<style>
.nw-wallet-page{max-width:1200px;margin:auto;padding:120px 28px 80px}.nw-wallet-hero{border-radius:30px;padding:clamp(1.7rem,4vw,3rem);margin-bottom:1.25rem;position:relative;overflow:hidden}.nw-wallet-hero::after{content:'';position:absolute;width:300px;aspect-ratio:1;left:2%;bottom:-30%;background:url('{{ asset('images/cinematic/nawader-moon-emblem-v1.webp') }}') center/contain no-repeat;opacity:.23}.nw-wallet-hero>*{position:relative;z-index:1}.nw-wallet-ledger{border-radius:24px;padding:1.5rem}.nw-wallet-table{width:100%;border-collapse:collapse}.nw-wallet-table th,.nw-wallet-table td{padding:1rem;text-align:right;border-bottom:1px solid rgba(255,255,255,.08)}.nw-wallet-table th{font-size:.74rem;color:var(--text-muted)}.nw-wallet-table td{font-size:.85rem}.nw-wallet-credit{color:var(--nawader-teal)}.nw-wallet-debit{color:#ff9bc0}@media(max-width:700px){.nw-wallet-page{padding:90px 18px 60px}.nw-wallet-table thead{display:none}.nw-wallet-table tr{display:block;padding:1rem 0;border-bottom:1px solid rgba(255,255,255,.08)}.nw-wallet-table td{display:block;padding:.25rem 0;border:0}.nw-wallet-table td::before{content:attr(data-label);color:var(--text-muted);font-size:.72rem;margin-left:.5rem}}
</style>
@endpush
@section('content')
<main class="nw-wallet-page"><header class="nw-wallet-hero nw-cinematic-panel"><div class="nw-section-eyebrow">دفتر العمليات</div><h1 class="nw-h1" style="margin:.6rem 0">المحفظة المالية</h1><p style="color:var(--text-secondary);max-width:620px">الرصيد أدناه محسوب من المعاملات المسجلة على حسابك؛ لا يتم إظهار أرقام حسابات أو قنوات دفع غير مهيأة.</p><div style="font:800 clamp(2.4rem,5vw,4.5rem) var(--font-latin);margin-top:1.2rem;color:#fff">{{ number_format($wallet['balance'],2) }} <span style="font-size:1rem;color:var(--nawader-gold)">ر.س</span></div><div style="color:var(--text-muted);margin-top:.35rem">ضمانات محتجزة مسجلة: {{ number_format($wallet['held'],2) }} ر.س</div></header><section class="nw-wallet-ledger nw-cinematic-panel"><div style="display:flex;justify-content:space-between;gap:1rem;align-items:start;margin-bottom:1rem"><div><h2 class="nw-h3">سجل المعاملات</h2><p style="font-size:.82rem;color:var(--text-muted)">كل قيد مرتبط بمحفظتك يظهر هنا عند تسجيله.</p></div><span class="nw-status">{{ $wallet['transactions_count'] }} معاملة</span></div><div style="overflow:auto"><table class="nw-wallet-table"><thead><tr><th>المرجع</th><th>الوصف</th><th>التاريخ</th><th>القيمة</th><th>الحالة</th></tr></thead><tbody>@forelse($transactions as $transaction) @php($credit = in_array($transaction->type,['deposit','cashback','escrow_release','refund'],true))<tr><td data-label="المرجع" style="font-family:var(--font-latin);color:var(--nawader-gold)">{{ $transaction->transaction_number }}</td><td data-label="الوصف">{{ $transaction->description ?: 'عملية مالية مسجلة' }}</td><td data-label="التاريخ">{{ $transaction->created_at->format('Y/m/d') }}</td><td data-label="القيمة" class="{{ $credit ? 'nw-wallet-credit' : 'nw-wallet-debit' }}" style="font-family:var(--font-latin);font-weight:800">{{ $credit ? '+' : '-' }}{{ number_format($transaction->amount,2) }} {{ $transaction->currency }}</td><td data-label="الحالة"><span class="nw-status">{{ $transaction->status }}</span></td></tr>@empty<tr><td colspan="5"><div class="nw-empty">لا توجد معاملات مسجلة في هذه المحفظة حتى الآن.</div></td></tr>@endforelse</tbody></table></div>{{ $transactions->links() }}</section></main>
@endsection
